name: ticats_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  firebase_core: ^3.6.0
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_debouncer: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_naver_map: ^1.3.0+1
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.2
  infinite_carousel: ^1.1.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  kakao_flutter_sdk_user: ^1.9.6
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  pub_semver: ^2.1.4
  retrofit: ^4.4.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.2
  talker: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  talker_riverpod_logger: ^4.4.1
  uuid: ^4.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  riverpod_generator: ^2.4.3

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 700
