// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASzTq9IFExQz4B2wOlIi3khplyxI7tg_g',
    appId: '1:900559920776:android:63afd9f7166014c824893d',
    messagingSenderId: '900559920776',
    projectId: 'ticats',
    storageBucket: 'ticats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQHsEoTg4XTMZ_5O4PTLh-D1u0CUIWj50',
    appId: '1:900559920776:ios:dd17fb2f2e8e453624893d',
    messagingSenderId: '900559920776',
    projectId: 'ticats',
    storageBucket: 'ticats.appspot.com',
    androidClientId: '900559920776-flob0a3cbl9rdl9r5gp63sa1clc3d7k8.apps.googleusercontent.com',
    iosClientId: '900559920776-buukmrjmls53plnhns88uakuglim68t7.apps.googleusercontent.com',
    iosBundleId: 'com.potatoes.ticatsApp',
  );

}